docs:
  - changed-files:
      - any-glob-to-any-file: ['docs/**', '**/*.md', '**/*.pdf']

feature:
  - head-branch: ['^feat', 'feat', '^feature', 'feature']

refactor:
  - head-branch: ['^refactor', 'refactor']

style:
  - head-branch: ['^style', 'style']

fix:
  - head-branch: ['^fix', 'fix']
