version: "3.8"
services:
  postgresql:
    image: postgres:16.3
    restart: always
    container_name: piikii_postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
