#  docker run -p 5432:5432 --name postgres-db \
#    -e POSTGRES_PASSWORD=112233 \
#    -e TZ=Asia/Seoul \
#    postgres:latest

spring:
  config:
    additional-location: classpath:/config/
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 112233
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect