name: CI

on:
  push:
    branches:
      - 'develop'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Repository 접근
        uses: actions/checkout@v4

      - name: JDK 21 셋팅
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 프로젝트 빌드
        env:
          REDIS_PORT: ${{ secrets.PROD_REDIS_PORT }}
          REDIS_HOST: ${{ secrets.PROD_REDIS_HOST }}
          DB_URL: ${{ secrets.PROD_DB_URL }}
          DB_USER: ${{ secrets.PROD_DB_USER }}
          DB_PASSWORD: ${{ secrets.PROD_PASSWORD }}
        run: |
          ./gradlew build
